/*
 Navicat Premium Data Transfer

 Source Server         : Localhost
 Source Server Type    : MySQL
 Source Server Version : 100406
 Source Host           : localhost:3306
 Source Schema         : bookstore

 Target Server Type    : MySQL
 Target Server Version : 100406
 File Encoding         : 65001

 Date: 28/12/2019 16:32:32
*/

SET NAMES utf8mb4
SET FOREIGN_KEY_CHECKS = 0

-- ----------------------------
-- Table structure for book
-- ----------------------------
DROP TABLE IF EXISTS book
CREATE TABLE book  (
  bookID int(6) NULL DEFAULT NULL,
  categoryID int(6) NULL DEFAULT NULL,
  discountID int(6) NULL DEFAULT NULL,
  name varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  author varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  published year NULL DEFAULT NULL,
  page int(255) NULL DEFAULT NULL,
  description varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  details varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  review double(255, 0) NULL DEFAULT NULL,
  image varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  price int(255) NULL DEFAULT NULL,
  quantity int(255) NULL DEFAULT NULL,
  highlight int(1) NULL DEFAULT NULL,
  new int(1) NULL DEFAULT NULL,
  active int(1) NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic

-- ----------------------------
-- Records of book
-- ----------------------------
INSERT INTO book VALUES (1, 4, 1, 'Pride and Prejudice', 'Jane Austen', 0000, 311, 'Austen\'s finest comedy of manners portrays life in the genteel rural society of the early 1800s, and tells of the initial misunderstandings (and mutual enlightenment) between lively and quick witted Elizabeth Bennet and the haughty Mr. Darcy.', 'Bennet,\" as she entered the room, \"we have had a most delightful evening, a most excellent ball. I wish you had been there. Jane was so admired, nothing could be like it. Everybody said how well she looked and Mr. Bingley thought her quite beautiful, and', 4, 'img/Books/001.jpg', 67, 50, 0, 0, 1)
INSERT INTO book VALUES (2, 4, 1, 'Emma', 'Jane Austen', 0000, 380, 'The main character, Emma Woodhouse, is described in the opening paragraph as \'\'handsome, clever, and rich\'\' but is also rather spoiled. As a result of the recent marriage of her former governess, Emma prides herself on her ability to matchmake, and procee', 'sly.\"\n\"Only one more, papa only for Mr. Elton. Poor Mr. Elton! You like Mr. Elton, papa,--I must look about for a wife for him. There is nobody in Highbury who deserves him--and he has been here a whole year, and has fitted up his house so comfortably, t', 4, 'img/Books/002.jpg', 24, 50, 0, 0, 1)
INSERT INTO book VALUES (3, 4, 1, 'Persuasion', 'Jane Austen', 0000, 150, 'Eight years ago, Anne Elliot fell in love with poor but ambitious naval officer Captain Frederick Wentworth -- a choice which Anne\'s family was dissatisfied with. Lady Russell, friend and mentor to Anne, persuaded the younger woman to break off the match', 's, as being Sir Walter, in her apprehension, entitled to a great deal of compassion and consideration under his present difficulties.\nThey must retrench that did not admit of a doubt. But she was very anxious to have it done with the least possible pain ', 5, 'img/Books/003.jpg', 33, 50, 0, 0, 1)
INSERT INTO book VALUES (4, 4, 1, 'Wuthering Heights', 'Emily Brontë', 0000, 300, 'Emily Brontë\'s only novel, this tale portrays Catherine and Heathcliff, their all-encompassing love for one another, and how this unresolved passion eventually destroys them both, leading Heathcliff to shun and abuse society. First published in 1847 under', 'assist him in counting his gold.\n\'I don\'t want your help,\' she snapped \'I can get them for myself.\'\n\'I beg your pardon!\' I hastened to reply.\n\'Were you asked to tea?\' she demanded, tying an apron over her neat black frock, and standing with a spoonful of', 4, 'img/Books/004.jpg', 32, 50, 1, 0, 1)
INSERT INTO book VALUES (5, 4, 1, 'Don Quixote', 'Miguel de Cervantes Saavedra', 0000, 1026, 'Translated by John Ormsby.\nOne of the earliest novels in a modern European language, one which many people consider the finest book in the Spanish language.', 'brown, spring out of the thicket with a goatherd after it, calling to it and uttering the usual cries to make it stop or turn back to the fold. The fugitive goat, scared and frightened, ran towards the company as if seeking their protection and then stood', 4, 'img/Books/005.jpg', 158, 50, 0, 0, 1)
INSERT INTO book VALUES (6, 4, 1, 'Jane Eyre', 'Charlotte Brontë', 0000, 497, 'A poor governess, Jane Eyre, captures the heart of her enigmatic employer, Edward Rochester. Jane discovers that he has a secret that could jeopardize any hope of happiness between them.', 'm grasp my hair and my shoulder: he had closed with a desperate thing. I really saw in him a tyrant, a murderer. I felt a drop or two of blood from my head trickle down my neck, and was sensible of somewhat pungent suffering: these sensations for the time', 5, 'img/Books/006.jpg', 178, 50, 0, 0, 1)
INSERT INTO book VALUES (7, 4, 1, 'Anna Karenina', 'graf Tolstoy Leo', 0000, 761, 'Anna is the jewel of St. Petersburg society until she leaves her husband for the handsome and charming military officer, Count Vronsky. They fall in love, going beyond High Society\'s acceptance of trivial adulterous dalliances. But when Vronsky\'s love coo', 'tic revolutionary hydra, but in the obstinacy of traditionalism clogging progress,\" etc., etc. He read another article, too, a financial one, which alluded to Bentham and Mill, and dropped some innuendoes reflecting on the ministry. With his characteristi', 5, 'img/Books/007.jpg', 174, 50, 0, 1, 1)
INSERT INTO book VALUES (8, 4, 1, 'Anthem', 'Ayn Rand', 1938, 70, '\"A dystopian fiction novella by Ayn Rand, first published in 1938. It takes place at some unspecified future date when mankind has entered another dark age as a result of the evils of irrationality and collectivism and the weaknesses of socialistic thinki', 'hey reach\ntheir fifteenth year. Then they go to work.\nIn the Home of the Students we arose when\nthe big bell rang in the tower and we went\nto our beds when it rang again. Before we\nremoved our garments, we stood in the\ngreat sleeping hall, and we raised o', 4, 'img/Books/008.jpg', 125, 50, 0, 1, 1)
INSERT INTO book VALUES (9, 4, 1, 'Don Quijote', 'Miguel de Cervantes Saavedra', 0000, 918, 'Don Quijote de la Mancha (ortografía y título original -1605-, El ingenioso hidalgo Don Quixote de la Mancha) es una de las obras cumbre de la literatura española y la literatura universal, el libro más traducido después de la Biblia, escrito por Miguel d', 'el\nvulgo, he determinado de sacar a luz al Ingenioso hidalgo don Quijote de la\nMancha, al abrigo del clarísimo nombre de Vuestra Excelencia, a quien, con\nel acatamiento que debo a tanta grandeza, suplico le reciba agradablemente\nen su protección, para que', 4, 'img/Books/009.jpg', 54, 50, 0, 0, 1)
INSERT INTO book VALUES (10, 4, 1, 'The Woman in White', 'Wilkie Collins', 0000, 615, 'The Woman in White is widely regarded as the first in the genre of \'sensation novels\'. It follows the story of two sisters living in Victorian England with their selfish, uninterested uncle as their guardian. Marian Halcombe is the elder of the two sister', 'his hand, the golden Papa has a letter and after he has made his excuse for disturbing us in our Infernal Region with the common mortal Business of the house, he addresses himself to the three young Misses, and begins, as you English begin everything in ', 4, 'img/Books/010.jpg', 54, 50, 0, 0, 1)
INSERT INTO book VALUES (11, 4, 1, 'The Phantom of the Opera', 'Gaston Leroux', 1911, 254, 'The story of a man named Erik, an eccentric, physically deformed genius who terrorizes the Opera Garnier in Paris. He builds his home beneath it and takes the love of his life, a beautiful soprano, under his wing.', 'a skeleton frame. His eyes are so deep that you can hardly see the fixed pupils. You just see two big black holes, as in a dead man\'s skull. His skin, which is stretched across his bones like a drumhead, is not white, but a nasty yellow. His nose is so li', 5, 'img/Books/011.jpg', 92, 50, 0, 0, 1)
INSERT INTO book VALUES (12, 4, 1, 'The Demon Girl', 'Penelope Fletcher', 2010, 208, 'Rae Wilder has problems. Plunged into a world of dark magic, fierce creatures and ritual sacrifice, she is charged with a guarding a magical amulet. Rae finds herself beaten up, repeatedly, and forced to make a choice: to live and die human, or embrace he', 'he truth. Let me go, you don\'t understand what will happen. My brothers-\"\nThe Lord Cleric punched her. Her head flew back and a spray of blood wet the dry mud and spattered over the leaves concealing me. Face wet with tears and whimpering, she tried to cr', 4, 'img/Books/012.jpg', 160, 50, 0, 0, 1)
INSERT INTO book VALUES (13, 4, 1, 'The Age of Innocence', 'Edith Wharton', 1920, 282, 'Among New York City\'s upper class of the 1870s, before the advent of electric lights, telephones or motor vehicles, there was a small cluster of aristocratic families that ruled New York\'s social life. To those at the apex of the social world one\'s occupa', 'beneath the rose-\ntrees and here and there a daisy grafted on a rose-\nbranch flowered with a luxuriance prophetic of Mr.\nLuther Burbank\'s far-off prodigies.\nIn the centre of this enchanted garden Madame\nNilsson, in white cashmere slashed with pale blue s', 4, 'img/Books/013.jpg', 175, 50, 0, 0, 1)
INSERT INTO book VALUES (14, 4, 1, 'Sense and Sensibility', 'Jane Austen', 0000, 304, 'Two sisters, Elinor and Marianne Dashwood (Elinor representing \'\'sense\'\' and Marianne \'\'sensibility\'\'), along with their mother and younger sister Margaret, are left impoverished after the death of their father, and the family is forced to move to a count', 'y give them occasionally will be of far greater assistance than a yearly allowance, because they would only enlarge their style of living if they felt sure of a larger income, and would not be sixpence the richer for it at the end of the year. It will cer', 4, 'img/Books/014.jpg', 184, 50, 0, 0, 1)
INSERT INTO book VALUES (15, 4, 1, 'A Voice in the Wilderness', 'Grace Livingston Hill', 1916, 260, 'Margaret Earle, an Eastern girl, thinking she has reached her destination in Arizona, where she is going to teach school, steps off the train at a lonely, desert water tank, and the train moves on, leaving her in the darkness and in a strange, forlorn lan', 'Is thet all yeh want o\' me? \'Cause ef \'tis I got t\' git on t\' camp. It\'s a good five mile yet, an\' I \'ain\'t hed no grub sence noon.\"\nThe tears suddenly rushed to the girl\'s eyes as the horror of being alone in the night again took possession of her. This ', 4, 'img/Books/015.jpg', 52, 50, 0, 1, 1)
INSERT INTO book VALUES (16, 4, 1, 'The Adventures of Sally', 'Pelham Grenville Wodehouse', 1922, 211, 'Being unaccustomed to owning a great deal of money, Sally hasn\'t got the hang of it yet. Which is why she agrees to backing a show written by her fiance Gerald and staged by her brother Fillmore. It seems like a good way of making them all happy... But wh', 'ore Nicholas had not worn well. At the age of seven he had been an extraordinarily beautiful child, but after that he had gone all to pieces and now, at the age of twenty-five, it would be idle to deny that he was something of a mess. For the three years', 4, 'img/Books/016.jpg', 66, 50, 0, 0, 1)
INSERT INTO book VALUES (17, 4, 1, 'Adam Bede', 'George Eliot', 0000, 478, 'The book which made Mrs. Carlyle feel \"in charity with the whole human race\" could be no ordinary one. Adam Bede contains all George Eliot\'s broad and catholic knowledge of life, and the characters are all drawn by the hand of a master.', 'Good evening.\"\nAdam hastened with long strides, Gyp close to his heels, out of the\nworkyard, and along the highroad leading away from the village and down\nto the valley. As he reached the foot of the slope, an elderly horseman,\nwith his portmanteau strapp', 0, 'img/Books/017.jpg', 114, 50, 0, 0, 1)
INSERT INTO book VALUES (18, 4, 1, 'The Abysmal Brute', 'Jack London', 1911, 87, 'A breezy tale showing the crookedness of the methods of prize-ring managers specially in fleecing the prize-ring public in betting. The hero is a successful young giant who has been trained by his father in the mountains, and who thinks the game is played', 'Stubener, \"an\' a trail that\'d break your heart.\"\nBreakfast consisted of black coffee, sourdough bread, and an immense quantity of bear-meat broiled over the coals. Of this the young fellow ate ravenously, and Stubener divined that both the Glendons were a', 5, 'img/Books/018.jpg', 102, 50, 0, 1, 1)
INSERT INTO book VALUES (19, 4, 1, 'Our Mutual Friend', 'Charles Dickens', 0000, 818, 'The story of the Harmon \'\'dust\'\' fortune and those who inherit it. Although somewhat a mystery, an important point concerning the identity of certain characters is revealed halfway through, without hinting as to the ending.', 'ine at Veneerings, expressly to meet the Member, the Engineer, the Payer-off of the National Debt, the Poem on Shakespeare, the Grievance, and the Public Office, and, dining, discovered that all of them were the most intimate friends Veneering had in the ', 0, 'img/Books/019.jpg', 60, 50, 0, 1, 1)
INSERT INTO book VALUES (20, 4, 1, 'Inside the Lines', 'Robert Welles Ritchie', 1915, 179, 'The story deals with an intrigue to blow up the English squadron at Gibraltar by gaining access to the room where the electrical contact with the harbor mines is made, and on this background Mr. Biggers paints a picture of the scenes following the outbrea', 'd\"--expressive Americanism, that,--under any handicap. She was a woman with a \"job\" Captain Woodhouse had never before met one such.\nAgain, here was a woman who tried none of the stale arts and tricks of coquetry no eyebrow strategy or maidenly simperin', 4, 'img/Books/020.jpg', 39, 50, 0, 0, 1)
INSERT INTO book VALUES (21, 4, 1, 'The House of Mirth', 'Edith Wharton', 1905, 327, 'One of the first novels of manners to emerge in American literature, and also one of Wharton\'s best-known works, The House of Mirth centers on Lily Bart, a New York socialite attempting to secure a husband and a place in affluent society.', 'I should fancy so--except to the historian. But your real collector values a thing for its rarity. I don\'t suppose the buyers of Americana sit up reading them all night--old Jefferson Gryce certainly didn\'t.\"\nShe was listening with keen attention. \"And ye', 4, 'img/Books/021.jpg', 56, 50, 0, 0, 1)
INSERT INTO book VALUES (22, 4, 1, 'He Fell In Love With His Wife', 'Edward Payson Roe', 0000, 273, 'The hero is a farmer--a man with honest, sincere views of life. Bereft of his wife, his home is cared for by a succession of domestics of varying degrees of inefficiency until, from a most unpromising source, comes a young woman who not only becomes his w', 'en thought of\nvery much else except the harmony and good comradeship which bless people who\nare suited to each other. He had been disappointed in no respect they had\ntoiled and gathered like ants they were confidential partners in the homely\nbusiness an', 5, 'img/Books/022.jpg', 176, 50, 0, 0, 1)
INSERT INTO book VALUES (23, 4, 1, 'Anna the Adventuress', 'E. Phillips Oppenheim', 1904, 215, 'Annabel Pellissier, for reasons of her own, allows Sir John Ferringhall to believe that she is her sister Anna. Anna lets the deception continue and has to bear the burden of her sister’s reputation which, in Paris at any rate, is that of being a coquette', 'dulgently.\n\"My dear child,\" he said, \"with me you need have no apprehension. I am almost old enough to be your father.\"\nShe looked at him with uplifted eyebrows--a look of whimsical incredulity. Sir John felt that after all forty-five was not so very old.', 4, 'img/Books/023.jpg', 123, 50, 1, 0, 1)
INSERT INTO book VALUES (24, 4, 1, 'The Border Legion', 'Zane Grey', 1916, 0, 'Jack Kells was a remorseless killer, head of a gang that ravaged the southern border. He didn\'t think twice before he kidnapped pretty Joan Randle on a lonesome Idaho trail. His cold eyes filled her with fear, but her goodness made something happen deep w', 'gone from camp to camp in Idaho--some too strange, too horrible for credence--and with every rumor the fame of Kells had grown, and also a fearful certainty of the rapid growth of a legion of evil men out on the border. But no one in the village or from a', 0, 'img/Books/024.jpg', 171, 50, 0, 1, 1)
INSERT INTO book VALUES (25, 4, 1, 'Twilight', 'Julia Frankau', 1916, 224, '\"Twilight\" is my swan song. I shall never write another novel. A year ago I fell into a consumption chiefly treated by morphia. I knew my De Quincey pretty well perhaps this game me this idea of writing my dreams. \"Twilight\" was written between 11 and 1 ', 'med a little startled at seeing me in her bed. The last thing I saw of her was a wavering smile, rather wonderful and alluring. I knew at once that she was Margaret Capel. But she was quickly replaced by two Chinese vases and a conventional design in blac', 0, 'img/Books/025.jpg', 184, 50, 0, 0, 1)
INSERT INTO book VALUES (26, 4, 1, 'Parnassus on Wheels', 'Christopher Morley', 1917, 100, 'The year is 1915. Our heroine is Helen McGill, a thirty-nine year old spinster who assists her brother Andrew in the running of his New England farm. Andrew is a literary man, however, and since his books have become successful, his attention to the farm ', 'not literary, as I said before, but I\'m human enough to like\na good book, and my eye was running along those shelves of his\nas I spoke. He certainly had a pretty miscellaneous collection.\nI noticed poetry, essays, novels, cook books, juveniles, school\nboo', 5, 'img/Books/026.jpg', 124, 50, 0, 0, 1)
INSERT INTO book VALUES (27, 4, 1, 'The Ragged Edge', 'Harold MacGrath', 1922, 215, 'This novel about China and the South Sea Islands is a thrilling character-story of literary excellence, which will further endear Mr. MacGrath to his widespread audience.', 'm that the young man might not be quite conscious of his surroundings, that he might be moving in that comatose state which is the aftermath of a long debauch. For all that, Ah Cum was forced to admit that his charge did not look dissipated.\nAh Cum was mo', 4, 'img/Books/027.jpg', 71, 50, 0, 0, 1)
INSERT INTO book VALUES (28, 4, 1, 'The Breaking Point', 'Mary Roberts Rinehart', 1922, 303, 'Elizabeth Wheeler lives in a small town, sings in the church choir, and dreams of a man who will sweep her off her feet. Instead, she is thrust into a series of events beyond her control leading to passion, madness, betrayal, and ultimately, murder! Can s', 'He must be in his office now. The light\'s burning.\"\n\"I wish you wouldn\'t, Clare. He\'d hate it if he knew.\"\nShe moved on and Clare slowly followed her. The Rossiter girl\'s flow of talk had suddenly stopped. She was thoughtful and impulsively suspicious.\n\"L', 4, 'img/Books/028.jpg', 38, 50, 1, 0, 1)
INSERT INTO book VALUES (29, 4, 1, 'The Curse of Capistrano', 'Julia Frankau', 1919, 226, 'The first work to feature Zorro, nobleman and master swordsman living in Spanish- and Mexican-era California. This novel originally appeared as five serialized installments in the pulp magazine All-Story Weekly.', 'ly before me here and now!\" the sergeant gasped.\nAnd again the door was opened suddenly, and a man entered the inn on a gust of the storm. \nChapter 3\nSenor Zorro Pays a Visit\nTHE NATIVE HURRIED forward to fasten the door against the force of the wind, and', 4, 'img/Books/029.jpg', 50, 50, 0, 0, 1)
INSERT INTO book VALUES (30, 4, 1, 'Ann Veronica', 'Robert Welles Ritchie', 1909, 320, 'Dealing with political issues of the time the novel was written and concentrating specifically on feminist issues, through the course this novel the heroine matures from an innocent and naïve girl to a representative of the New Woman.', 'ightly and joyfully as one who commonly and habitually feels well, and sometimes she stooped a little and was preoccupied. Her lips came together with an expression between contentment and the faintest shadow of a smile, her manner was one of quiet reserv', 0, 'img/Books/030.jpg', 90, 50, 0, 0, 1)
INSERT INTO book VALUES (31, 4, 1, 'Affinities', 'Pelham Grenville Wodehouse', 1920, 181, 'Five short stories dealing with the escapades of society women in America and England. CONTENTS:I AFFINITIESII THE FAMILY FRIENDIII CLARA\'S LITTLE ESCAPADEIV THE BORROWED HOUSEV SAUCE FOR THE GANDER', 'nough for me, with Day out of town but the rest of them never had any luck and they had to get that car.\n\"They\'re terribly nervous, all at once!\" I said. \"If that car goes without me, Ferd, I shall jump into the river!\"\nIt was moonlight, but not very bri', 4, 'img/Books/031.jpg', 41, 50, 0, 0, 1)
INSERT INTO book VALUES (32, 4, 1, 'Jack Sheppard', 'Charles Dickens', 0000, 468, 'A celebrated thief is the un-worthy hero of this early dramatic romance.', 'ly. \"I\'m sure little Jack has but one friend beside myself, in the world, and that\'s more than I would have ventured to say for him yesterday. However, I\'ve not told you all for old Van did say something about the child saving his new-found friend\'s life', 0, 'img/Books/032.jpg', 123, 50, 1, 0, 1)
INSERT INTO book VALUES (33, 4, 1, 'Wild Irish Heart', 'Inez Haynes Gillmore', 2014, 210, 'It is time…\n\nAn ancient book, a power untouched, and a heart unloved lead Keelin O\'Brien from her graduate studies in Boston to a small village on the coast of Southern Ireland. Determined to unearth the secrets lying hidden in the enchanted waters of the', '', 5, 'img/Books/033.jpg', 45, 50, 0, 0, 1)
INSERT INTO book VALUES (34, 4, 1, 'The Call of the Canyon', 'Zane Grey', 1924, 179, 'Glenn Killbourne and his fiancee Carley Burch find a strange test of their love in the mountains and canyons of Arizona.', 'some one had drawn up her window shades. Carley promptly pulled them down and settled herself comfortably. Then she heard a woman speak, not particularly low: \"I thought people traveled west to see the country.\" And a man replied, rather dryly. \"Wal, not ', 5, 'img/Books/034.jpg', 165, 50, 0, 0, 1)
INSERT INTO book VALUES (50, 3, 1, 'Thuvia Maid of Mars', 'Edgar Rice Burroughs', 1920, 148, 'This installment shifts focus from John Carter and Dejah Thoris, protagonists of the first three books in the series, to their son Carthoris, prince of Helium, and to Thuvia, princess of Ptarth, and follows Carthoris\' efforts to win the heart of Thuvia, w', 'that the point rests upon the exact latitude and longitude of Helium. Then I start the engine, roll up in my sleeping silks and furs, and with lights burning, race through the air toward Helium, confident that at the appointed hour I shall drop gently tow', 3, 'img/Books/050.jpg', 27, 50, 0, 0, 1)
INSERT INTO book VALUES (51, 3, 1, 'After London', 'Jane Austen', 0000, 204, 'After some sudden and unspecified catastrophe has depopulated England, the countryside reverts to nature, and the few survivors to a quasi-medieval way of life. Beginning with a loving description of nature reclaiming England -- fields becoming overrun by', 'ound their dogs abandon the fold, and join the wild troops that fell upon the sheep. The black wood-dogs hunt in packs of ten or more (as many as forty have been counted), and are the pest of the farmer, for, unless his flocks are protected at night withi', 4, 'img/Books/051.jpg', 195, 50, 0, 0, 1)
INSERT INTO book VALUES (52, 3, 1, 'Atlantis: The Antedeluvian World', 'Ignatius Donnelly', 0000, 354, 'This book is an attempt to demonstrate several distinct and novel propositions. These are:1. That there once existed in the Atlantic Ocean, opposite the mouth of the Mediterranean Sea, a large island, which was the remnant of an Atlantic continent, and kn', 'g us or among yourselves. As for those genealogies of yours which you have recounted to us, Solon, they are no better than the tales of children for, in the first place, you remember one deluge only, whereas there were many of them and, in the next plac', 5, 'img/Books/052.jpg', 90, 50, 0, 0, 1)
INSERT INTO book VALUES (53, 3, 1, 'Planet of the Damned', 'Harry Harrison', 1962, 157, 'Hugo nominated in 1962, originally published in Analog Science Fact-Science Fiction as \"Sense of Obligation.\" Brion has just won the Twenties, a global competition to test achievements in 20 categories of human activities -- but before he can enjoy his vi', 'both of these noble institutions without an instant\'s thought. All of you haven\'t a single thought for the past, for the untold billions who led the bad life as mankind slowly built up the good life for you to lead. Do you ever think of all the people who', 4, 'img/Books/053.jpg', 149, 50, 1, 0, 1)
INSERT INTO book VALUES (54, 3, 1, 'A Journey to the Interior of the Earth', 'Jane Austen', 0000, 495, 'Translated by Frederick Amadeus Malleson in 1877.', 'scientific specimens and stones too, enough to rebuild entirely the house in Königstrasse, even with a handsome additional room, which would have suited me admirably.\nBut on entering this study now I thought of none of all these wonders my uncle alone f', 3, 'img/Books/054.jpg', 157, 50, 1, 0, 1)
INSERT INTO book VALUES (55, 3, 1, 'The Dreams in the Witch-House', 'H. P. Lovecraft', 1933, 34, '', 'a discussion of possible freakish curvatures in space, and of theoretical points of approach or even contact between our part of the cosmos and various other regions as distant as the farthest stars or the transgalactic gulfs themselves--or even as fabulo', 4, 'img/Books/055.jpg', 35, 50, 0, 0, 1)
INSERT INTO book VALUES (56, 3, 1, 'The 4-D Doodler', 'Graph Waldeyer', 1941, 24, 'Do you believe, Professor Gault, that this four dimensional plane contains life--intelligent life?', 'He stared blankly at Harper, then his hands slowly came up to clutch at his stomach.\nHarper looked quickly at the desk top.\n\"The other orange,\" he gasped. \"It\'s gone!\"\n\"Into--my--stomach!\" groaned Pillbot. \"Be--be careful what you do! My God, don\'t do any', 4, 'img/Books/056.jpg', 63, 50, 0, 0, 1)
INSERT INTO book VALUES (57, 3, 1, 'Star Maker', 'Olaf Stapledon', 1937, 424, 'At a moment when Europe is in danger of a catastrophe worse than that of 1914 a book like this may be condemned as a distraction from the desperately urgent defence of civilization against modern barbarism.', 'se they were so near. On every side the middle distance was crowded with swarms and streams of stars. But even these now seemed near for the Milky Way had receded into an incomparably greater distance. And through gaps in its nearer parts appeared vista ', 4, 'img/Books/057.jpg', 27, 50, 0, 0, 1)
INSERT INTO book VALUES (58, 3, 1, 'All Around the Moon', 'Jules Verne', 0000, 277, 'Translated by Edward Roth', 'with Chief Engineer Murphy\'s, who had been charged to fire off the Projectile.\n\"Friends,\" he said, \"it is now twenty minutes past ten. At 10 46\' 40\'\', precisely, Murphy will send the electric current into the gun-cotton. We have, therefore, twenty-six min', 3, 'img/Books/058.jpg', 140, 50, 0, 0, 1)
INSERT INTO book VALUES (59, 3, 1, 'Ancient and Modern Physics', 'Thomas E. Willson', 1901, 70, '', 'ti, which is in\ntouch with each one of the four globes and a part of it. The\nsame is true of any aggregation of prakriti--of the earth itself\nand of all things in it, including man. As there are four\natoms in each one, so there are four earths, four globe', 3, 'img/Books/059.jpg', 53, 50, 0, 0, 1)
INSERT INTO book VALUES (60, 3, 1, 'A Martian Odyssey', 'Stanley Grauman Weinbaum', 1949, 34, 'A science-fiction classic.', 'at the earth on my diagram, and then at myself, and then, to clinch it, I pointed to myself and then to the earth itself shining bright green almost at the zenith.\n\"Tweel set up such an excited clacking that I was certain he understood. He jumped up and d', 5, 'img/Books/060.jpg', 154, 50, 0, 0, 1)
INSERT INTO book VALUES (61, 3, 1, 'The Time Traders', 'Andre Norton', 1958, 178, 'Intelligence agents have uncovered something beyond belief, but the evidence is incontrovertible: the USA’s greatest adversary is sending its own agents back through time! And someone (or something) is presenting them with technologies and weapons far bey', '..\" droned the voice. Ross realized that he must have missed something, not that it mattered. He was almost determined not to play along any more.\nThere was a click, signifying that Kelgarries was through braying. But the customary silence did not close i', 4, 'img/Books/061.jpg', 107, 50, 0, 0, 1)
INSERT INTO book VALUES (62, 3, 1, 'The Colors of Space', 'Marion Zimmer Bradley', 1963, 144, 'It was a week before the Lhari ship went into warp-drive, and all that time young Bart Steele had stayed in his cabin. He was so bored with his own company that the Mentorian medic was a welcome sight when he came to prepare him for cold-sleep!', 'the Lhari that way, yet they\'re as human as we are! Slaves of the Lhari!\"\nBart felt the involuntary surge of anger, instantly controlled. \"It\'s not that way at all. My mother was a Mentorian, remember. She made five cruises on a Lhari ship before she marr', 4, 'img/Books/062.jpg', 59, 50, 1, 0, 1)
INSERT INTO book VALUES (63, 3, 1, 'Ventus', 'Karl Schroeder', 2007, 652, 'A novel of information apocalypse set in the far future. For a thousand years the sovereign Winds have maintained the delicate ecological balance of the terraformed planet Ventus. Now an alien force threatens to wrest control of the terraforming system aw', 'not monsters. That one was just trying to protect itself.\"\n\"What was that silver stuff? It looked alive!\"\n\"Dad told me about that one time. The mothers protect themselves with it. He said the stuff goes towards whatever\'s wettest. He said he saw somebody ', 5, 'img/Books/063.jpg', 57, 50, 0, 0, 1)
INSERT INTO book VALUES (64, 3, 1, 'Corvus', 'L. Lee Lowe', 2010, 460, 'In an alternate present the minds of teen offenders are uploaded into computers for rehabilitation--a form of virtual wilderness therapy. Zach is a homo cognoscens, one of the new humans who can navigate the Fulgrid. Though still a high school student, he', 'entor at university, then Litchfield himself, synthesised in order to activate what would, in certain cases, become momentous germline mutations.\n* * *\n\'Get up, lad. You\'ll freeze to death like this.\'\nZach raises his head. His skin and lips are already nu', 3, 'img/Books/064.jpg', 191, 50, 0, 0, 1)
INSERT INTO book VALUES (65, 3, 1, 'Buddy Holly is Alive and Well on Ganymede', 'Bradley Denton', 1991, 322, 'When televisions worldwide begin broadcasting a nonstop, noninterruptible live performance by Buddy Holly purporting to originate somewhere in the vicinity of Jupiter, Oliver Vale--the apparent object of the broadcasts--finds himself drafted for a mission', 'ill be most pleased as she ships you off to the state hospital at Osawatomie!\"\nBuddy took a few steps back from the camera and shifted the Strat into playing position. \"That\'s all the sign says, but I\'ll repeat the address in a while in case nobody\'s list', 4, 'img/Books/065.jpg', 169, 50, 0, 0, 1)
INSERT INTO book VALUES (66, 3, 1, 'The Ware Tetralogy', 'Jane Austen', 2010, 881, 'Your Guide to the 21st Century!It starts with Software, where rebel robots bring immortality to their human creator by eating his brain. Software won the first Philip K. Dick Award.In Wetware, the robots decide to start building people­—and people get str', 'Call him Cobb Anderson2. Cobb2 didn\'t drink. Cobb envied him. He hadn\'t had a completely sober day since he had the operation and left his wife.\n\"How did you get here?\"\nThe robot waved a hand palm up. Cobb liked the way the gesture looked on someone else.', 5, 'img/Books/066.jpg', 40, 50, 0, 0, 1)
INSERT INTO book VALUES (67, 3, 1, 'The Airlords of Han', 'Philip Francis Nowlan', 1928, 94, 'It was no accident that Buck Rogers became an almost instantaneous success as a comic strip. Behind its creation was one of the most logical, scientifically planned \"worlds of if\" ever conceived. The re-presentation of these original Buck Rogers stories s', 'ry in our advance on Nu-Yok.\nFortunately our contact guard had been able to leap into the upper branches of a tree without being discovered by the Bad Bloods, for their discipline was lax and their guard careless. She overheard enough of the conversation ', 4, 'img/Books/067.jpg', 168, 50, 0, 0, 1)
INSERT INTO book VALUES (68, 3, 1, 'Angel Island', 'Inez Haynes Gillmore', 1914, 356, '', 'of libertine. Woman, first and foremost, was\nhis game. Every woman attracted him. No woman held him. Any new woman,\nhowever plain, immediately eclipsed her predecessor, however beautiful.\nThe fact that amorous interests took precedence over all others was', 3, 'img/Books/068.jpg', 31, 50, 0, 0, 1)
INSERT INTO book VALUES (69, 3, 1, 'Acid Bath', 'Vaseleos Garson', 1952, 24, 'The starways\' Lone Watcher had expected some odd developments in his singular, nerve-fraught job on the asteroid. But nothing like the weird twenty-one-day liquid test devised by the invading Steel-Blues.', 'f the cylinder.\nA square, glass-like tumbler sat in the opening disclosed in the four-foot cylinder that had sprouted tentacles. It contained a yellowish liquid.\nOne of the tentacles reached into the opening and clasped the glass. The opening closed and t', 2, 'img/Books/069.jpg', 183, 50, 0, 0, 1)
INSERT INTO book VALUES (70, 3, 1, 'Bad Medicine', 'Robert Sheckley', 1956, 33, 'The classic SF story wherein a man is mistakenly treated by a Martian psychotherapy machine. Copyright (c) 2003 by Robert Sheckley, originally published 1956.', 'ed iron.\n\"What do you want?\" Lieutenant Smith asked.\nThe ugly man flipped back his lapel, showing a small silver badge\nbeneath. \"I\'m John Rath, General Motors Security Division.\"\n\"Oh ... Sorry, sir,\" Lieutenant Smith said, saluting. \"I didn\'t think you\npe', 4, 'img/Books/070.jpg', 140, 50, 0, 0, 1)
INSERT INTO book VALUES (71, 3, 1, '(Nothing But) Flowers', 'John G. McDaid', 2009, 38, '', 'ow long ago? He marveled at how the priestesses had managed to keep this one icon in pristine condition. He could understand why the pilgrims felt\nthe magic in it, even if he did not.\n\"Estamos refugiados en una zona de apagon.\" The priestess, in a high, s', 3, 'img/Books/071.jpg', 178, 50, 0, 0, 1)
INSERT INTO book VALUES (72, 3, 1, 'Armageddon—2419 A.D.', 'Philip Francis Nowlan', 1928, 85, 'The original \"Buck Rogers\" story -- Nowlan’s novella tells about America in the 25th century, conquered by Hans in 2109 A.D. and only now beginning to rebel. The Hans are invaders from Asia with highly advanced technology. They have great aircraft armed w', 'rybody belong to a gang nowadays?\"\n\"Naturally,\" she said, frowning. \"If you don\'t belong to a gang, where and how do you live? Why have you not found and joined a gang? How do you eat? Where do you get your clothing?\"\n\"I\'ve been eating wild game for the p', 4, 'img/Books/072.jpg', 94, 50, 0, 0, 1)
INSERT INTO book VALUES (73, 3, 1, '--And Devious the Line of Duty', 'Tom Godwin', 1962, 49, 'Sometimes the most diligent and loyal thingan old man can do is fumble, drink beer, and let a young man get into trouble....', 'the New Jardeen Incident.\"\nA frozen silence followed the last five words. Hunter thought, So that\'s what the little weasel was fishing for....\nRockford quietly laid down his fork. Val\'s face turned grim. Lyla looked up in quick alarm and said to Narf:\n\"Le', 4, 'img/Books/073.jpg', 155, 50, 0, 0, 1)

SET FOREIGN_KEY_CHECKS = 1
