INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (0, 'Best seller', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (1, 'Recomment', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (2, 'Scient', 23, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (3, 'Romance', 34, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (4, 'Fantasy', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (5, 'History', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (6, 'Humor & comedy', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (7, 'Action & adventure', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (8, 'Mystery & Thriller', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (9, 'Comic', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (10, 'Non-fiction', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (11, 'Scient-fiction', 50, 1);
INSERT INTO `category`(`categoryID`, `name`, `quantity`, `active`) VALUES (12, 'Literary', 50, 1);
